### ISSUE TITLE
Error cannot import 'BaseSpider' from 'scrapy.spiders'

### ISSUE THREAD

**Issue by robyg72** [PacktPublishing/Learning-Python-Web-Penetration-Testing#4]
Hello,
I'm following tutorials from the book and I'm facing an issue with first exercise from Chapter 3.
My box is a Linux Debian release 10, Python 3.8 and Scrapy 2.2.0.
I haven't changed anything from the sample code.

![Cattura](https://user-images.githubusercontent.com/8139414/86770463-05c67e80-c051-11ea-801b-34481d33eb6a.PNG)

Can you help, please?
Thanks

**Comment by laramies** [comment]
Hi @robyg72  I need to look further, but at first glance, seems that the latest version of Scrappy changed considerably the inner workings.  I recommend to follow the training with the VM provided.
